<?php 

$parte = $_POST['parte'];

switch($parte){
    case "cabeza":
        $resultado = '{ "textos":[{"titulo":"Head Pressing","contenido":"Se trata de un problema neurológico, especialmente del prosencéfalo o cerebro primitivo anterior, que es la porción anterior del cerebro durante la fase de desarrollo del embrión y que está presente en casi todos los mamíferos. Si vemos a nuestro perro apoyando su cabeza contra la pared, el suelo o algún otro objeto capaz de sustentarle, durante un lapso de tiempo prolongado, es posible que estemos ante un caso de head pressing. Si bien la causa subyacente de este comportamiento puede variar, el head pressing en perros, se debe a un fuerte dolor de cabeza. Del mismo modo que los humanos nos apretamos las sienes cuando esta nos duele, algunos animales tratan de aliviarse presionándola contra algo que les ofrezca resistencia."}
        ,{"titulo":"Hidrocefalia","contenido":"La hidrocefalia, como su propio nombre indica, consiste en la acumulación de líquido cefalorraquídeo en lo que se denominan ventrículos cerebrales. Esto hace que aumenten de tamaño y, así, dañan la corteza cerebral al comprimirla contra los huesos del cráneo. La mayoría de los casos de hidrocefalia son congénitos, pero hay otros adquiridos que se desencadenan a partir de un traumatismo, infecciones que afectan al cerebro o tumores. Es importante que sepamos que algunos perros tendrán más predisposición a sufrir este trastorno de una manera congénita. Así, es el caso de la hidrocefalia en chihuahuas o la hidrocefalia en perros pug, yorkshire, maltés, lhasa apso, pomerania, etc., porque son razas toy o de pequeño tamaño. Lo mismo sucede en la hidrocefalia en perros bulldog, en este caso por la conformación braquicéfala de su cabeza. Es decir, el tamaño y la forma del cráneo influyen en la presentación de esta patología."}
        ,{"titulo":"Traumatismo Craneoencefálico","contenido":" El trauma craneoencefálico es una las causas más frecuentes de morbilidad y mortalidad en perros y gatos tras un accidente. El reconocimiento rápido y correcto de los signos clínicos indicativos de un dañointracraneal así como la instauración de un tratamiento rápido y adecuado es crítico para ofrecer el mejor pronóstico. Se abordará qué sucede en el cerebro tras un traumatismo craneoencefálico, qué signos clínicos nos permiten reconocer los daños producidos y qué pautas de tratamiento deben ser instauradas para garantizar la mejor recuperación del paciente."}
        ,{"titulo":"Epilepsia","contenido": "La epilepsia en perros es un trastorno neurológico que se origina por perturbaciones en la formación y transmisión de estímulos por los grupos de células nerviosas en determinadas partes del cerebro. Se afirma que un perro tiene epilepsia cuando, por ejemplo, se producen al menos dos ataques epilépticos con más de 24 horas de diferencia. La epilepsia no es desencadenada por ninguna causa específica, y hay tantos orígenes de la enfermedad como perros que la sufren. El problema que está detrás de la epilepsia es un defecto genético, frecuentemente hereditario, que crea los problemas en el cerebro. Además, hay algunas razas que son más propensas que otras debido a sus genes recesivos, como los Cocker Spaniel, Beagles o Pastores Belgas, entre otras. Suele decirse que las razas de perros grandes sufren epilepsia con más frecuencia que las medianas y pequeñas, pero esto no está del todo claro. Sí se sabe que la incidencia de la enfermedad es mayor entre los machos que entre las hembras, aunque ningún perro está libre de sufrirla."}
        ,{"titulo":"Estrabismo","contenido": "El estrabismo se define como un trastorno en la coordinación del globo ocular y se caracteriza porque los ojos no se dirigen simultáneamente hacia el mismo objetivo. Los perros pueden sufrir diversos tipos de estrabismo:Estrabismo divergente: Los ojos se desvían hacia afuera.Estrabismo convergente: Los ojos se desvían hacia dentro.Estrabismo dorsal: Los ojos se desvían hacia arriba.Estrabismo ventral: Los ojos se desvían hacia abajo."}
        ,{"titulo":"Convulsiones","contenido": "Las convulsiones en perros, al igual que en el ser humano, son crisis de origen nervioso que representen las emergencias caninas nerviosas más frecuentes. Las convulsiones se asocian una alteración de la actividad motora con desordenes de la sensibilidad y de la consciencia. Debemos saber que las convulsiones en los perros pueden tener diversas causas y, dependiendo de la que esté afectando a nuestro perro, el veterinario prescribirá un tratamiento u otro"}] }';
         break;
    case "cola":
        $resultado = '{ "textos":[{"titulo":"Fractura","contenido":"La fractura es la lesión más frecuente en la cola del perro.Generalmente se debe a un pisotón accidental o a que se le ha enganchado o pillado con alguna puerta.Aunque dolorosa, este tipo de lesión suele curarse por sí sola y la parte fracturada calcifica bien. En ocasiones, pueden quedar señales (protuberancias) que suelen ser molestas al principio para el animal,  por lo que deberemos procurar no tocarle la cola.Es posible que le cueste hacer sus necesidades, precisamente por el grado de implicación que tienen los músculos de la cola para defecar y miccionar. Salvo casos más graves, esta dificultad remite pronto."}
        ,{"titulo":"Sangrado de cola","contenido":"Otra de las lesiones en la cola del perro más frecuentes es el sangrado, especialmente en las razas grandes. Esto sucede porque los perros no pueden evitar mover la cola y se la golpean contra diversos objetos y personas, provocándose en ocasiones úlceras sangrantes.En este caso, resulta importante desinfectar la cola y dejar la zona de la herida vendada (cambiando el vendaje cada dos o tres días), hasta que se cure completamente. También puede ser aconsejable utilizar un producto anti-lamidos (como manzana amarga) o un collar isabelino, para evitar que el perro se hurgue en la cola. A veces el sangrado en la cola puede deberse a que el perro se la muerda con excesiva frecuencia debido a una infestación de pulgas o de garrapatas, en cuyo caso, después de desinfectar y vendar la zona dañada, deberemos abordar el problema de los parásitos."}
        ,{"titulo":"Síndrome de la cola fría o partida","contenido":"Razas como la Golden Retriever,  Labrador, Beagle,  Setter inglés, Pointer son propensas a padecer esta dolencia. Es propia de los perros nadadores.Se trata de un problema muscular, no de hueso. Los síntomas son: Cola caída como si estuviera partida, dolorida y muy sensibilizada.Si bien, no se conocen exactamente las causas que provocan este síndrome, parece ser que tienen que ver con ellas, los esfuerzos muy intensos, el frío del agua y la humedad. Se piensa que también influye el transporte en jaulas de este tipo de razas, especialmente cuando el animal es muy activo y juguetón. Ante un caso de “cola partida”,  no debemos tocar la cola del perro.Generalmente no necesita más que algo de reposo y se cura a los pocos días."}] }';
        break;
    case "patas delanteras":
        $resultado = '{ "textos":[{"titulo":"Infección causada por Levadura","contenido":"Se presenta como una de las infecciones más frecuentes de hallar en las patas de los perros. Es causada por hongos pertenecientes a levaduras del género Malassezia, microorganismos capaces de sobrevivir en la piel del can sin causarle daños, aunque, si por cualquier motivo llegan a reproducirse, entonces sí que aparecerán las infecciones. Los perros que están inmunodeprimidos exhiben más posibilidades de padecer la presencia de estos hongos, especialmente durante el verano, cuando el clima se torna más caluroso. Las concentraciones de agentes infecciosos suelen aparecer en las patas de los canes, más específicamente en sus dedos, donde se presenta una humedad mayor. También es frecuente que se infecten los oídos de los perros. El principal síntoma de este problema infeccioso en las patas de los perros es la intensa comezón que experimentan. Por ello, con frecuencia podemos sorprender a nuestra mascota rascarse con tesón.  Por otra parte, las áreas corporales afectadas por las infecciones causadas por levaduras expondrán una tonalidad rojiza y la piel lucirá bastante maltratada. Así también, estas zonas dañadas de la piel por lo general emiten un desagradable olor."}
        ,{"titulo":"La sarna demodécica","contenido":"Por lo que se refiere a la sarna demodécica, se trata de una enfermedad que es causada por un ácaro denominado como Demodex canis, el cual habita en el interior de los folículos pilosos del can. Por otra parte, hay tres clases de sarna demodécica, una de las cuáles es conocida como pododermatitis demodécica, misma que afecta directamente a las patas del animal. Por la presencia de ese ácaro y las lesiones que este produce en la piel, se presentan infecciones bacterianas de tipo secundario, especialmente entre los dedos del can o en sus almohadillas. Otros síntomas que puede experimentar un perro con sarna demodécica son las calvas en la piel, costras, llagas, lesiones, entre varias más. Los canes de manera natural suelen tener ácaros en su pelaje, por lo consiguiente, el veterinario solamente diagnosticará sarna si aparecen lesiones en la piel del perro, además de visualizar a los ácaros tras haber realizado una biopsia o un raspado."}] }';
        break;
    case "patas traseras":
        $resultado = '{ "textos": [{"titulo":"Micosis (Piel)","contenido":"Entre algunos de los tipos de dermatitis que se pueden dar en perro, está la micosis, misma que comienza en las patas del perro, concretamente debajo de las uñas, y prolifera hasta extenderse por todo el cuerpo (en algunos casos). Ante la duda, te aconsejamos que revises las patas de tu perro en busca de sarpullidos con forma de círculo y sin pelo. Como acción preventiva, es importante que le seques muy bien después del baño o de un paseo por el río, la humedad es el ambiente ideal para que los hongos proliferen. El tratamiento suele ser un champú especial y medicación específica."}
        ,{"titulo":"Alergias","contenido":"Antes la presencia de alergia verás a tu perro rascarse, a menudo el vientre, los costados y las orejas, o frotarse la cara y morderse las patas. Su piel se inflamará (dermatitis) y se pueden desarrollar lesiones e infecciones en la piel tu perro, incluida la posible pérdida de cabello y un tono de piel oscuro. Las alergias pueden ocurrir en cualquier etapa durante la vida de tu perro. Algunas razas están predispuestas a desarrollar alergias, incluyendo West Highland White Terriers, Wirehaired Fox Terriers, Golden Retrievers, Labrador Retrievers, Lhasa Apsos, Bulldogs, English Setters, Boxers, Dalmatians y Shar-Peis, principalmente."}
        ,{"titulo":"Parálisis","contenido":"El porqué un perro no tiene fuerza en las patas traseras puede deberse a un problema agudo, es decir, que aparece de repente, dejando al animal inmovilizado o con las patas muy debilitadas. No son patologías muy frecuentes. Entre ellas destacarían las siguientes: Parálisis por garrapatas: algunas de las garrapatas que puede padecer el perro contienen un tóxico en su saliva que afecta a los nervios motores, los debilita o los paraliza. Comienza afectando a las patas traseras pero la parálisis asciende al punto de provocar una parada respiratoria. Botulismo: se trata de una enfermedad paralizante causada por neurotoxinas que produce la bacteria Clostridium botulinum. Los perros pueden contraerla al ingerir carroña o alimentos mal enlatados. El pronóstico depende del grado de afectación. Miastenia grave: es una enfermedad que afecta a la movilidad muscular a nivel del sistema nervioso. La debilidad que causa es generalizada, pero se visualiza mejor en las patas traseras. El perro se tambalea al andar y le cuesta levantarse. Hay una forma autoinmune de la enfermedad que puede producirse junto a hipotiroidismo."}] }';
        break;
    case "tronco":
        $resultado = '{ "textos":[{"titulo":"Disnea","contenido":"La disnea leve no siempre es fácil de detectarlos síntomas pueden ser un mayor uso de los músculos abdominales durante la respiración, tolerancia reducida al esfuerzo, depresión y pérdida del apetito. En caso de disnea más grave, el perro respira con la boca abierta, utiliza los músculos abdominales para respirar y suele mantenerse de pie o sentado en lugar de tumbarse. Los perros con disnea aguda o grave están frecuentemente afectados, y el mínimo empeoramiento de su estado puede resultar letal en el peor de los casos. Si eso ocurre, tratar al perro con calma y cuidado, y acudir inmediatamente a un hospital veterinario.Una vez que se ha comprobado que el perro presenta disnea, el veterinario trata de averiguar si los problemas respiratorios son más pronunciados al inhalar o exhalar, y si la causa subyacente está presente en las vías respiratorias superiores o inferiores."}
        ,{"titulo":"Hepatitis primaria","contenido":"Poco se sabe sobre la etiología, evolución, resultados de los tratamientos y factores que afectan el pronóstico en perros con esa hepatitis. En un estudio retrospectivo realizado en 101 perros con hepatitis primaria confirmada histológicamente se informó de la aparición de hepatitis aguda en 21 perros y crónica en 67. En 43 perros fue idiopática (64 %) y en 24 (36 %) se asoció a acumulación de cobre. La media de supervivencia fue mayor en la forma aguda. La mayoría de los casos fueron crónicos"}
        ,{"titulo":"Leptospirosis","contenido":"La leptospirosis es una enfermedad infecciosa, producida por bacterias del género Leptospira, que afecta a animales domésticos y silvestres. Es una zoonosis de gran distribución mundial, donde los perros actúan de manera importante en la transmisión de la leptospirosis al hombre, especialmente en zonas urbanas. Las leptospiras, son microorganismos que miden 0,1 micras de espesor por 7 a 14 micras de longitud, terminadas en ganchos, son extremadamente móviles, y se clasifican en más de 200 serovares patógenos. Los animales infectados eliminan las leptospiras por la orina, contaminan el medio e infectan a los animales susceptibles. Ingresan al organismo a través de la piel y mucosas, en el canino por el comportamiento social de lamer los genitales de los congéneres, y olfatear los árboles. "}
        ,{"titulo":"Cálculos renales","contenido":"Empezamos el repaso de los problema renales en los perros por los cálculos, que no son más que piedras de diferentes tamaños que se forman por la precipitación de algunos minerales. En este proceso influye la alimentación, el pH y la hidratación. Los cálculos renales producen dolor, dificultades a la hora de miccionar o incontinencia, sangre en la orina, presencia de arenilla en la orina, etc. En ocasiones, incluso, es posible observar la expulsión de algún cálculo que, como recomendación, deberemos llevar a la clínica veterinaria para ser analizado con el fin de descubrir la causa de su formación. Si no se controlan pueden provocar perforaciones, obstrucciones y fallo renal. El tratamiento va a depender del tipo de cálculo, puesto que son varios los que existen en función de su composición (de calcio, de estruvita, de ácido úrico, etc.)."}
        ,{"titulo":"Pielonefritis","contenido":"Este problema renal en los perros consiste en una infección de riñón causada por bacterias que va a afectar también al uréter. Lo habitual es que se produzca por complicación de una infección de vejiga, lo que implica que las bacterias han ascendido desde ella hasta los riñones. Por otro lado, puede haber una obstrucción o una malformación de nacimiento que favorezca la aparición de estas infecciones. La enfermedad puede aparecer de manera aguda o crónica. En el primer caso, los síntomas incluyen fiebre, anorexia, vómitos y dolor en la zona baja del lomo y al orinar. El perro adopta una postura anormal con las patas rígidas y el cuerpo encorvado. La pielonefritis crónica puede presentarse o no tras una aguda. El cuadro clínico se caracteriza por anorexia, adelgazamiento, eliminación de una mayor cantidad de orina e incremento en la ingesta de agua."}
        ,{"titulo":"Nefritis y nefrosis","contenido":"Otro de los problemas renales en los perros son las enfermedades que van a afectar a los riñones al punto de llegar a la insuficiencia renal. En concreto, la nefritis es una inflamación que se asocia a enfermedades como la hepatitis, la erliquiosis, la pancreatitis o la borreliosis. En cambio, la nefrosis se debe a cambios degenerativos consecuencia de una intoxicación como, por ejemplo, por el consumo de algunos medicamentos. En ambos casos los perros presentarán síndrome nefrótico, con edema, ascitis y derrame pleural. La nefritis puede resolverse tratando de manera precoz la causa que la ha desarrollado. Para el síndrome nefrótico se actúa como en la insuficiencia renal, que veremos en el siguiente apartado."}
        ,{"titulo":"Insuficiencia cardíaca","contenido":"La insuficiencia cardíaca se define como retrógrada, si se empiezan a acumular líquidos en el cuerpo, o anterógrada, si no es posible mantener una presión arterial normal. La retrógrada (también llamada «insuficiencia congestiva») es la forma más común y suele provocar una acumulación de líquido en los pulmones (edema pulmonar) y más raramente en la cavidad torácica, fuera de los pulmones (efusón pleural), líquido en el abdomen (ascitis) o líquido en el pericardio (efusión pericardica).Los perros ​casi nunca acumulan líquido (edema) en las extremidades, como suelen hacerlo los humanos con insuficiencia cardíaca."}
        ,{"titulo":"Alteraciones atlantoaxiales y síndrome de tambaleo","contenido":"Se presenta cuando la articulación del atlas con el axis, que son las dos primeras vertebras cervicales, se ven afectadas en su movilidad. Debemos recordar que la articulación de estas dos estructuras óseas permite movimientos rotacionales de la cabeza sobre la columna.Cuando la cabeza es forzada hacia abajo, es decir ventralmente, se pueden producir diversas lesiones, como la ruptura de ligamentos, fractura de una parte de las vértebras llamadas apófisis o del cuerpo del axis, o una mezcla de todas estas lesiones. Este tipo de lesiones suelen ser provocadas por traumatismos que se pueden presentar a cualquier edad, como resultado de una fuerza de flexión sobre la cabeza. Se requiere una fuerza considerable para precipitar tal traumatismo en perros normales."}] }';
        break;
        
}

echo $resultado;

?>

